"""
Audit trail endpoints — query event log + generate PDF report.
"""

from __future__ import annotations

import io
import json
import logging
from datetime import datetime, time, timezone

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from fpdf import FPDF
from pydantic import BaseModel
from starlette.concurrency import run_in_threadpool

from api.deps import require_admin
from db.postgres import get_pool

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/audit-trail", tags=["audit"])


def _start_of_day(date_str: str) -> datetime:
    return datetime.combine(datetime.fromisoformat(date_str).date(), time.min, tzinfo=timezone.utc)


def _end_of_day(date_str: str) -> datetime:
    return datetime.combine(datetime.fromisoformat(date_str).date(), time.max, tzinfo=timezone.utc)


@router.get("")
async def get_audit_trail(
    from_date: str | None = Query(None),
    to_date: str | None = Query(None),
    entity_type: str | None = Query(None),
    page: int = 1,
    limit: int = 50,
    user: dict = Depends(require_admin),
) -> dict:
    pool = await get_pool()
    conditions = ["org_id = $1"]
    params: list = [user["org_id"]]
    idx = 2

    if from_date:
        conditions.append(f"timestamp >= ${idx}")
        params.append(_start_of_day(from_date))
        idx += 1
    if to_date:
        conditions.append(f"timestamp <= ${idx}")
        params.append(_end_of_day(to_date))
        idx += 1
    if entity_type:
        conditions.append(f"entity_type = ${idx}")
        params.append(entity_type)
        idx += 1

    where = " AND ".join(conditions)

    async with pool.acquire() as conn:
        rows = await conn.fetch(
            f"""
            SELECT audit_log.id, actor_id, u.username AS actor_name, actor_role,
                   entity_type, entity_id, action, details, timestamp
            FROM audit_log
            LEFT JOIN users u ON u.id::text = audit_log.actor_id
            WHERE {where}
            ORDER BY timestamp DESC
            LIMIT {limit} OFFSET {(page - 1) * limit}
            """,
            *params,
        )
        total = await conn.fetchval(
            f"SELECT COUNT(*) FROM audit_log WHERE {where}",
            *params,
        )

    def _parse_details(raw):
        if isinstance(raw, (dict, list)) or raw is None:
            return raw
        try:
            return json.loads(raw)
        except (ValueError, TypeError):
            return raw

    items = []
    for r in rows:
        items.append({
            "id": str(r["id"]),
            "actor_id": r["actor_id"],
            "actor_name": r["actor_name"],
            "actor_role": r["actor_role"],
            "entity_type": r["entity_type"],
            "entity_id": r["entity_id"],
            "action": r["action"],
            "details": _parse_details(r["details"]),
            "timestamp": r["timestamp"].isoformat(),
        })

    return {"items": items, "total": total, "page": page, "limit": limit}


class ReportRequest(BaseModel):
    from_date: str
    to_date: str


def _build_pdf(rows: list[dict], from_date: str, to_date: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Auditly — Compliance Audit Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Period: {from_date}  to  {to_date}", ln=True, align="C")
    pdf.ln(6)

    # Table header
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font("Helvetica", "B", 9)
    col_w = [35, 25, 20, 20, 35, 45]
    headers = ["Timestamp", "Actor", "Role", "Entity", "Action", "Details"]
    for w, h in zip(col_w, headers):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for r in rows:
        ts = r["timestamp"][:16].replace("T", " ")
        actor = r["actor_id"][-8:]  # last 8 chars of user id
        role = r["actor_role"].replace("org:", "")
        entity = f"{r['entity_type']}/{r['entity_id']}"[:16]
        action = r["action"]
        details = str(r.get("details") or "")[:40]

        row_data = [ts, actor, role, entity, action, details]
        for w, v in zip(col_w, row_data):
            pdf.cell(w, 6, v[:30], border=1)
        pdf.ln()

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, f"Generated by Auditly  |  Total events: {len(rows)}", ln=True, align="R")

    return bytes(pdf.output())


@router.post("/report")
async def generate_report(
    body: ReportRequest,
    user: dict = Depends(require_admin),
) -> StreamingResponse:
    pool = await get_pool()

    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT actor_id, actor_role, entity_type, entity_id, action, details, timestamp
            FROM audit_log
            WHERE org_id = $1
              AND timestamp >= $2
              AND timestamp <= $3
            ORDER BY timestamp ASC
            LIMIT 1000
            """,
            user["org_id"],
            _start_of_day(body.from_date),
            _end_of_day(body.to_date),
        )

    if not rows:
        raise HTTPException(404, "No audit events found for the given date range")

    row_dicts = [
        {
            "actor_id": r["actor_id"],
            "actor_role": r["actor_role"],
            "entity_type": r["entity_type"],
            "entity_id": r["entity_id"],
            "action": r["action"],
            "details": r["details"],
            "timestamp": r["timestamp"].isoformat(),
        }
        for r in rows
    ]

    pdf_bytes = await run_in_threadpool(_build_pdf, row_dicts, body.from_date, body.to_date)

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=audit-report-{body.from_date}.pdf"},
    )
